[package]
name = "snarkvm-algorithms"
version = "0.5.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Algorithms for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[[bench]]
name = "msm-variable-base"
path = "benches/msm/variable_base.rs"
harness = false

[[bench]]
name = "commitment-pedersen"
path = "benches/commitment/pedersen.rs"
harness = false

[[bench]]
name = "crh-pedersen"
path = "benches/crh/pedersen.rs"
harness = false

[[bench]]
name = "crh-bowe-pedersen"
path = "benches/crh/bowe_pedersen.rs"
harness = false

[[bench]]
name = "fft"
path = "benches/fft/fft.rs"
harness = false

[[bench]]
name = "prf-blake2s"
path = "benches/prf/blake2s.rs"
harness = false

[[bench]]
name = "signature-schnorr"
path = "benches/signature/schnorr.rs"
harness = false

[[bench]]
name = "snark-gm17"
path = "benches/snark/gm17.rs"
harness = false

[[example]]
name = "gm17"
path = "examples/snark/gm17.rs"

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.5.5"
default-features = false

[dependencies.snarkvm-fields]
path = "../fields"
version = "0.5.5"
default-features = false

[dependencies.snarkvm-profiler]
path = "../profiler"
version = "0.5.5"
default-features = false

[dependencies.snarkvm-r1cs]
path = "../r1cs"
version = "0.5.5"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.5.5"
default-features = false

[dependencies.blake2]
version = "0.9"
optional = true

[dependencies.derivative]
version = "2"

[dependencies.digest]
version = "0.9"

[dependencies.itertools]
version = "0.10.1"

[dependencies.rand]
version = "0.8"

[dependencies.rand_chacha]
version = "0.3"
default-features = false

[dependencies.rayon]
version = "1"

[dependencies.sha2]
version = "0.9"
default-features = false

[dependencies.smallvec]
version = "1.6"

[dependencies.cuda-oxide]
version = "0.4"
optional = true

[dependencies.lazy_static]
version = "1.4"

[dependencies.crossbeam-channel]
version = "0.5"

[dependencies.thiserror]
version = "1.0"

[dependencies.bitvec]
version = "0.22"

[dependencies.once_cell]
version = "1.8"

[dev-dependencies.criterion]
version = "0.3.4"

[dev-dependencies.csv]
version = "1"

[dev-dependencies.rand_xorshift]
version = "0.3"

[features]
default = [
  "full",
  "parallel",
  "snarkvm-curves/default",
  "snarkvm-fields/default",
  "snarkvm-r1cs/default",
  "snarkvm-utilities/default"
]
full = [
  "commitment",
  "commitment_tree",
  "crh",
  "encoding",
  "encryption",
  "fft",
  "merkle_tree",
  "msm",
  "prf",
  "signature",
  "snark"
]
wasm = [
  "commitment",
  "commitment_tree",
  "crh",
  "encoding",
  "encryption",
  "fft",
  "merkle_tree",
  "msm",
  "prf",
  "signature",
  "snark"
]
commitment = [ "blake2", "crh" ]
commitment_tree = [ ]
crh = [ ]
encoding = [ ]
encryption = [ "signature" ]
fft = [ ]
merkle_tree = [ ]
msm = [ ]
prf = [ "blake2" ]
signature = [ "encryption" ]
snark = [ "fft", "msm" ]
parallel = [ ]
print-trace = [ "snarkvm-profiler/print-trace" ]
cuda = [ "cuda-oxide" ]
